In [ ]:
#1convert a list of numeric value into a one-dimensional numpy array
import numpy as np
lst = [12.23, 13.32, 100, 36.32]
ar = np.array(lst,dtype=int)
print(ar)

[ 12  13 100  36]


In [ ]:
#1Create a 3x3 matrix with values ranging from 2 to 10.
three_d_array = [[ 2 ,3 ,4] ,
[ 5 ,6 ,7], 
[ 8 ,9 ,10]]
print(three_d_array)

three_d_array2 = np.random.randint(2,10,(3,3))
print(three_d_array2)

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]
[[6 3 7]
 [8 2 8]
 [4 5 7]]


In [ ]:
#3Update sixth value to 11 
arr = np.zeros(10)
print(arr)
arr[6] = 11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [ ]:
#4 Python program to reverse an array
arr =np.array([12, 13 ,14, 1,5 ,16 ,17, 18, 19, 20, 21, 22, 23 ,24, 25, 26 ,27, 28, 29, 30 ,31 ,32 ,33, 34 ,35 ,36 ,37] )
new_arr = arr[::-1]
print(new_arr)
reverse = np.flip(arr)
print(reverse)
print(arr)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16  5  1
 14 13 12]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16  5  1
 14 13 12]
[12 13 14  1  5 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37]


In [ ]:
#5 middle as zero
arr = np.ones((5,5))
arr[1:len(arr)-1:1, 1:len(arr)-1:1]=0
print(arr)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#6 border as zero
arr = np.random.randint(1,10,(10,10))

arr[0,0:]=0
arr[len(arr)-1,0:]= 0
for i in range(1,len(arr)-1):
    arr[i,0]= 0
    arr[i,len(arr[1])-1] = 0
print(arr)


arr2 = np.random.randint(1,10,(5,5))
rows, cols = arr2.shape
vborder = np.zeros((1,cols))
arr2 = np.vstack((vborder, arr2 ,vborder))
hborder = np.zeros((rows+2,1))
arr2 = np.hstack((hborder,arr2,hborder))
print(arr2)



[[0 0 0 0 0 0 0 0 0 0]
 [0 4 7 1 2 9 9 3 9 0]
 [0 2 4 5 5 7 1 2 8 0]
 [0 6 5 8 7 4 5 8 7 0]
 [0 9 9 4 5 4 8 1 2 0]
 [0 8 6 8 3 3 9 8 4 0]
 [0 7 2 5 1 4 3 3 2 0]
 [0 7 8 6 6 6 7 2 4 0]
 [0 1 6 5 1 7 1 5 4 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 6. 1. 8. 4. 0.]
 [0. 3. 5. 6. 2. 9. 0.]
 [0. 9. 4. 4. 9. 2. 0.]
 [0. 3. 7. 1. 6. 6. 0.]
 [0. 9. 8. 1. 1. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#7 chess board
board = np.ones((8,8),dtype=int)
board[0::2,0::2] = 0
board[1::2,1::2] = 0
print(board)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#8 convert list to array and tuple to array
lst = [1,2,3,4,5,6,7,8] 
arr = np.array(lst,dtype=int)
print(arr)
tpl = ([[8,4,6],[1,2,3]])
arr2 = np.array(tpl)
print(arr2)



[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [ ]:
#9 concatinate elements
arr = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80,90])
arr4 = np.append(arr,arr2)
print(arr4)

arr3 = np.concatenate([arr,arr2],axis=0)
print(arr3)

[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]


In [ ]:
# 10 real and imaginary part
arr= np.array([1.00000000+0.j, 0.70710678+0.70710678j])
real = arr.real
imag = arr.imag
print("Real part of the array:  \n",real)

print("Imaginary part of the array: \n",imag)



Real part of the array:  
 [1.         0.70710678]
Imaginary part of the array: 
 [0.         0.70710678]


In [ ]:
# 11 Size, byte of array
arr = np.array([10,20,30])
size = arr.size
b = arr.itemsize
total = arr.nbytes
# total = size*b

print(f'''Size of the array: {3} 
Length of one array element in bytes: {b}  
Total bytes consumed by the elements of the array: {total}''')

Size of the array: 3 
Length of one array element in bytes: 8  
Total bytes consumed by the elements of the array: 24


In [55]:
#12 unique elements
arr1 = np.array( [0,10,20,40,60])
arr2 = np.array([10, 30, 40, 50, 70, 90])
arr3 = np.intersect1d(arr2,arr1)
print(arr3)



[10 40]


In [56]:
arr1 = np.array( [ 0, 10 ,20 ,40 ,60 ,80]) 
arr2 = np.array([10, 30, 40, 50, 70, 90])
arr3 = np.setdiff1d(arr1,arr2)
print(arr3)

[ 0 20 60 80]
