In [16]:
#1convert a list of numeric value into a one-dimensional numpy array
import numpy as np
lst = [12.23, 13.32, 100, 36.32]
ar = np.array(lst)
print(ar)

[ 12.23  13.32 100.    36.32]


In [3]:
#2 Create a 3x3 matrix with values ranging from 2 to 10.
three_d_array = np.array([[ 2 ,3 ,4] ,
                          [ 5 ,6 ,7], 
                          [ 8 ,9 ,10]])
print(three_d_array)
three_d_array2 = np.random.randint(2,10,(3,3))
print(three_d_array2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[6 9 9]
 [9 5 3]
 [8 4 2]]


In [ ]:
#3 Update sixth value to 11 
arr = np.zeros(10)
print(arr)
arr[6] = 11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [5]:
#4 Python program to reverse an array
arr =np.array([12, 13 ,14, 1,5 ,16 ,17, 18, 19, 20, 21, 22, 23 ,24, 25, 26 ,27, 28, 29, 30 ,31 ,32 ,33, 34 ,35 ,36 ,37] )
new_arr = arr[::-1]
print(new_arr)
reverse = np.flip(arr)
print(reverse)
print(arr)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16  5  1
 14 13 12]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16  5  1
 14 13 12]
[12 13 14  1  5 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37]


In [6]:
#5 middle as zero
arr = np.ones((6,6))
arr[1:len(arr)-1:1, 1:len(arr)-1:1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [7]:
#6 border as zero
arr = np.random.randint(1,10,(10,10))

arr[0,0:]=0
arr[len(arr)-1,0:]= 0
for i in range(1,len(arr)-1):
    arr[i,0]= 0
    arr[i,len(arr[1])-1] = 0
print(arr)

arr2 = np.random.randint(1,10,(5,5))
rows, cols = arr2.shape
vborder = np.zeros((1,cols))
arr2 = np.vstack((vborder, arr2 ,vborder))
hborder = np.zeros((rows+2,1))
arr2 = np.hstack((hborder,arr2,hborder))
print(arr2)

[[0 0 0 0 0 0 0 0 0 0]
 [0 7 4 2 7 4 9 3 4 0]
 [0 1 3 2 7 7 4 1 1 0]
 [0 3 8 5 5 5 7 2 2 0]
 [0 2 3 8 6 7 8 6 6 0]
 [0 9 8 4 6 4 4 1 5 0]
 [0 3 5 7 9 6 7 9 3 0]
 [0 5 9 7 3 1 9 3 3 0]
 [0 1 4 1 4 7 3 9 3 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 2. 9. 9. 2. 0.]
 [0. 7. 1. 6. 2. 4. 0.]
 [0. 3. 8. 1. 2. 1. 0.]
 [0. 2. 1. 6. 8. 6. 0.]
 [0. 2. 6. 1. 8. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [8]:
#7 chess board
board = np.ones((8,8),dtype=int)
board[0::2,0::2] = 0
board[1::2,1::2] = 0
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
#8 convert list to array and tuple to array
lst = [1,2,3,4,5,6,7,8] 
arr = np.array(lst,dtype=int)
print(arr)
tpl = ([[8,4,6],[1,2,3]])
arr2 = np.array(tpl)
print(arr2)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [10]:
#9 concatinate elements
arr = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80,90])
arr4 = np.append(arr,arr2)
print(arr4)

arr3 = np.concatenate([arr,arr2],axis=0)
print(arr3)

[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]


In [11]:
# 10 real and imaginary part
arr= np.array([1.00000000+0.j, 0.70710678+0.70710678j])
real = arr.real
imag = arr.imag
print("Real part of the array:  \n",real)
print("Imaginary part of the array: \n",imag)

Real part of the array:  
 [1.         0.70710678]
Imaginary part of the array: 
 [0.         0.70710678]


In [12]:
# 11 Size, byte of array
arr = np.array([10,20,30])
size = arr.size
b = arr.itemsize
total = arr.nbytes
# total = size*b
print(f'''Size of the array: {3} 
Length of one array element in bytes: {b}  
Total bytes consumed by the elements of the array: {total}''')

Size of the array: 3 
Length of one array element in bytes: 8  
Total bytes consumed by the elements of the array: 24


In [13]:
#12 common elements
arr1 = np.array( [0,10,20,40,60])
arr2 = np.array([10, 30, 40, 50, 70, 90])
arr3 = np.intersect1d(arr2,arr1)
print(arr3)

[10 40]


In [14]:
#13 unique elements
arr1 = np.array( [ 0, 10 ,20 ,40 ,60 ,80]) 
arr2 = np.array([10, 30, 40, 50, 70, 90])
arr3 = np.setdiff1d(arr1,arr2)
print(arr3)

[ 0 20 60 80]


In [15]:
#14 setExclusive-or different elements in sorted order
arr1 = [0,10,20,40,60,80]  
arr2 = [10,30,40,50,70] 
arr3 = np.setdiff1d(arr1,arr2)
arr4 = np.setdiff1d(arr2,arr1)
print(np.sort(np.concatenate([arr3, arr4], axis=0)))

print(np.setxor1d(arr1,arr2))

[ 0 20 30 50 60 70 80]
[ 0 20 30 50 60 70 80]


In [16]:
#15.a conditions in numpy
a =np.array( [1,2] )
b = np.array([4,5]) 
result = np.where(a > b,True,False)  
print(result)
result2 = np.where(a >= b, True, False)  
print(result2)
result3 = np.where(a < b ,True,False)
print(result3)
result4 = np.where(a<=b,True,False)  
print(result4)

# print(np.logical_and(a > b, a >= b ))
# print(np.logical_and(a < b, a <= b))

[False False]
[False False]
[ True  True]
[ True  True]


In [17]:
#15.b write an array i to a file 
import csv
arr1 = np.array([ 0, 10 ,20 ,40 ,60 ,80],dtype="int32") 
with open("numpy.csv","w") as f:
    csv.writer(f).writerow(arr1)
    f.write
with open("numpy.csv","r") as f:
    arr2 = csv.reader(f)
    for i in arr2:
        print(np.array(i,dtype="int32"))

np.savetxt("numpy.txt",arr1)
a = np.loadtxt("numpy.txt",delimiter=",")
print(a)


[ 0 10 20 40 60 80]
[]
[ 0. 10. 20. 40. 60. 80.]


In [18]:
#16 convert an arrray into 1d array
arr1 = np.array([[10,20,30],  
[20 ,40 ,50]] ) 
print(arr1.flatten())
print(arr1.ravel())
print(arr1.reshape(1,6))

[10 20 30 20 40 50]
[10 20 30 20 40 50]
[[10 20 30 20 40 50]]


In [19]:
#17 convert int32 to float64
arr1 = np.array([[2,4,6],
[6,8,10]])
print(f"{arr1}\n Data type of the array arr1 is: {arr1.dtype}")  
arr2 = np.array(arr1,dtype="float64")
print(f"{arr2}\n Data type of the array arr1 is: {arr2.dtype}")  


[[ 2  4  6]
 [ 6  8 10]]
 Data type of the array arr1 is: int64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
 Data type of the array arr1 is: float64


In [20]:
#18 making daignol elements as 1
arr1 = np.zeros((6,6))
for i in range(len(arr1)):
    arr1[i][i] = 1
print(arr1)

arr2 = np.zeros((6,6))
np.fill_diagonal(arr2,1)
print(arr2)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [21]:
#19 given lower triangle pattern
arr1 = np.ones((4,3))
arr2 = np.tril(arr1,k=-1)
print(arr2)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [22]:
#20 concatinate two dimensional array
arr1 = np.array(([[0, 1, 3],
                 [5, 7, 9]] , 
                 [[0, 2, 4], 
                 [6, 8, 10]]))
print(np.array([np.append(arr1[0][0],arr1[1][0]),np.append(arr1[0][1],arr1[1][1])]))
print(np.array([np.concatenate((arr1[0][0],arr1[1][0])),np.concatenate((arr1[0][1],arr1[1][1]))]))

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [23]:
#21 make an array as immutable
arr1 = np.array([ 5,7,9,6,8,10])
arr1.setflags(write = False)
arr1[0]=6
print(arr1)

ValueError: assignment destination is read-only

In [ ]:
#22  multiply every element with 3
def mul(x):
   return x*3

arr1 = np.random.randint(2,9,(3,4))
arr2 = np.ones((3,4))
arr3 =np.vectorize(mul)(arr1)
arr4 = np.vectorize(mul)(arr2)
print(arr1)
print(arr3)
print(arr2)
print(arr4)

[[6 7 3 3]
 [8 5 8 8]
 [4 7 2 5]]
[[18 21  9  9]
 [24 15 24 24]
 [12 21  6 15]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [ ]:
#23 convert array to a list
arr1 = np.array([[0,1],[2,3],[4,5]])
arr2 = arr1.tolist()
print(arr2)

[[0, 1], [2, 3], [4, 5]]


In [ ]:
#24 convert array to list 
arr1 = np.array([ 0.26153123, 0.52760141 ,0.5718299 ,0.5927067, 0.7831874 ,0.69746349 ,
0.35399976 ,0.99469633 ,0.0694458 ,0.54711478])
arr2 = np.round(np.array(arr1,dtype="float"),3).tolist()
print(type(arr2))
print(arr2)

<class 'list'>
[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]


In [28]:
#25
arr1 = np.array([ 1.60000000e-10 ,1.60000000e+00 ,1.20000000e+03, 2.35000000e-01] ) 
arr2 = np.round(arr1,3)
np.set_printoptions(suppress= True, precision=3)
print(arr1)
print(arr2)

[   0.       1.6   1200.       0.235]
[   0.       1.6   1200.       0.235]


In [29]:
#26 Add Extra Column
arr1 = np.array([[ 10, 20, 30, 100] ,
[ 40 ,50 ,60 ,200]] )
arr2 = np.column_stack((arr1,np.ones((2,1))))
print(arr2)

[[ 10.  20.  30. 100.   1.]
 [ 40.  50.  60. 200.   1.]]


In [ ]:
#27 Remove Elements
arr1 = np.array([ 10 ,20, 30 ,40 , 50, 60, 70, 80, 90, 100] )
arr2 = np.delete(arr1,[0,3,4])
print(arr2)

[ 20  30  60  70  80  90 100]


In [46]:
# NumPy (Intermediate)
#  A weather station stores hourly temperature readings for 7 days in a NumPy array of shape (7, 24).
# Task:
# Find the daily maximum and minimum temperature
# Identify the day with the largest temperature variation
# Replace outliers beyond ±2 standard deviations with the mean temperature
temperatures = np.random.randint(1,100,(7,24))
print(temperatures)
highest = 0
day = 0
for i in range(0,7):
    high_temp = temperatures[i,0::].max()
    min_temp = temperatures[i,0::].min()
    print(f"Temperatures of day {i+1} is \n max temperature = {high_temp} \n min temperature = {min_temp}")
    if high_temp >= highest:
        highest = high_temp
        day = i+1
print(f"Day: {day} is the day with highest Temperature with {highest} Among 7 days")
mean = temperatures.mean()
print(mean)
std = temperatures.std()
sd1 =  2 * std
sd2 =  -2 * std
temperatures = np.array(np.where(temperatures > sd1, mean_temp, temperatures),dtype = int)
temperatures = np.array( np.where(temperatures < sd2, mean_temp, temperatures),dtype = int)

[[78 36 60 64 70 82 38 40 68 65 94 58 86 14 86 78 29 42  2 55 58 21 13 45]
 [82 97 22 32 43 14 33  8  8 89 20 26  9 89 11 64 91 92 85 36 96  3 83  9]
 [69 25 18 34 82 41 33 42 90 55 50 98 31 53 17 16 31 75 28 14  3 80 97 94]
 [78 98 38 47 33 69 98 38 14 28 32 69  2  7 41 43 63 23 98 63  3 20 19 77]
 [89 70 22  8 89 42 23  9 23 20 43 76 89 63 55 26  5 27 62  4 15 89 26 88]
 [10 26 86 24  9 90 40  6 89 56 92 93 60 29 48 60 80 11 74 67 77 38 79 65]
 [ 1 89 68 47 24 20  6 52 94 31 75 25 37  8 76 25 49 35 30  7 58  3 14 12]]
Temperatures of day 1 is 
 max temperature = 94 
 min temperature = 2
Temperatures of day 2 is 
 max temperature = 97 
 min temperature = 3
Temperatures of day 3 is 
 max temperature = 98 
 min temperature = 3
Temperatures of day 4 is 
 max temperature = 98 
 min temperature = 2
Temperatures of day 5 is 
 max temperature = 89 
 min temperature = 4
Temperatures of day 6 is 
 max temperature = 93 
 min temperature = 6
Temperatures of day 7 is 
 max temperature = 94 
 min 

In [44]:
print(temperatures)

[[ 5 52 52 52 52  8 19 52 52 52  2 52 52 44 52 52 52 52 40 38 52 52 52 23]
 [52  3 52 52 56 52  1 52 52 52 39 51 52 52 16 47 16 52 10 52  3 43 38 10]
 [55 18 52 26 27 52 34 55 52 53 52 52 56 52 52 43 52 52 39 49 52 53 46 29]
 [52 52 13 52 39 52 52 52 13 52 52 52 30 56 52 25 52 12 46 52 52 52  4 52]
 [52 52 52 52 52 46 52 27 52 52 21 52 52 52 52  3 25  6 36 52 31 52 17 52]
 [52 42 27 12 50 52 52  9  3 52 52 36 19 42 52 16 43 20 52 17 52 28 40 46]
 [ 4 18 52 33 36 52 52 33 52 52 18 52 23 29  8 31 23 30 52 49 52 52 32  7]]
