In [ ]:
#1convert a list of numeric value into a one-dimensional numpy array
import numpy as np
lst = [12.23, 13.32, 100, 36.32]
ar = np.array(lst,dtype=int)
print(ar)

[ 12  13 100  36]


In [ ]:
#1Create a 3x3 matrix with values ranging from 2 to 10.
three_d_array = [[ 2 ,3 ,4] ,
[ 5 ,6 ,7], 
[ 8 ,9 ,10]]
print(three_d_array)

three_d_array2 = np.random.randint(2,10,(3,3))
print(three_d_array2)

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]
[[6 6 8]
 [7 9 7]
 [7 4 2]]


In [3]:
#3Update sixth value to 11 
arr = np.zeros(10)
print(arr)
arr[6] = 11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [4]:
#4 Python program to reverse an array
arr =np.array([12, 13 ,14, 1,5 ,16 ,17, 18, 19, 20, 21, 22, 23 ,24, 25, 26 ,27, 28, 29, 30 ,31 ,32 ,33, 34 ,35 ,36 ,37] )
new_arr = arr[::-1]
print(new_arr)
reverse = np.flip(arr)
print(reverse)
print(arr)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16  5  1
 14 13 12]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16  5  1
 14 13 12]
[12 13 14  1  5 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37]


In [5]:
#5 middle as zero
arr = np.ones((5,5))
arr[1:len(arr)-1:1, 1:len(arr)-1:1]=0
print(arr)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
#6 border as zero
arr = np.random.randint(1,10,(10,10))

arr[0,0:]=0
arr[len(arr)-1,0:]= 0
for i in range(1,len(arr)-1):
    arr[i,0]= 0
    arr[i,len(arr[1])-1] = 0
print(arr)


arr2 = np.random.randint(1,10,(5,5))
rows, cols = arr2.shape
vborder = np.zeros((1,cols))
arr2 = np.vstack((vborder, arr2 ,vborder))
hborder = np.zeros((rows+2,1))
arr2 = np.hstack((hborder,arr2,hborder))
print(arr2)



[[0 0 0 0 0 0 0 0 0 0]
 [0 8 8 3 6 5 3 4 5 0]
 [0 4 9 1 2 1 6 7 5 0]
 [0 1 2 8 2 6 8 7 2 0]
 [0 9 8 4 7 9 5 8 4 0]
 [0 6 2 5 9 7 3 8 7 0]
 [0 8 1 2 1 8 1 5 4 0]
 [0 4 3 4 2 7 8 3 2 0]
 [0 5 7 3 9 5 1 2 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 2. 5. 2. 2. 0.]
 [0. 4. 9. 5. 9. 3. 0.]
 [0. 7. 2. 2. 7. 2. 0.]
 [0. 4. 9. 6. 6. 7. 0.]
 [0. 3. 7. 7. 6. 7. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [7]:
#7 chess board
board = np.ones((8,8),dtype=int)
board[0::2,0::2] = 0
board[1::2,1::2] = 0
print(board)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
#8 convert list to array and tuple to array
lst = [1,2,3,4,5,6,7,8] 
arr = np.array(lst,dtype=int)
print(arr)
tpl = ([[8,4,6],[1,2,3]])
arr2 = np.array(tpl)
print(arr2)



[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [9]:
#9 concatinate elements
arr = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80,90])
arr4 = np.append(arr,arr2)
print(arr4)

arr3 = np.concatenate([arr,arr2],axis=0)
print(arr3)

[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]


In [10]:
# 10 real and imaginary part
arr= np.array([1.00000000+0.j, 0.70710678+0.70710678j])
real = arr.real
imag = arr.imag
print("Real part of the array:  \n",real)

print("Imaginary part of the array: \n",imag)



Real part of the array:  
 [1.         0.70710678]
Imaginary part of the array: 
 [0.         0.70710678]


In [11]:
# 11 Size, byte of array
arr = np.array([10,20,30])
size = arr.size
b = arr.itemsize
total = arr.nbytes
# total = size*b

print(f'''Size of the array: {3} 
Length of one array element in bytes: {b}  
Total bytes consumed by the elements of the array: {total}''')

Size of the array: 3 
Length of one array element in bytes: 8  
Total bytes consumed by the elements of the array: 24


In [12]:
#12 unique elements
arr1 = np.array( [0,10,20,40,60])
arr2 = np.array([10, 30, 40, 50, 70, 90])
arr3 = np.intersect1d(arr2,arr1)
print(arr3)



[10 40]


In [13]:
arr1 = np.array( [ 0, 10 ,20 ,40 ,60 ,80]) 
arr2 = np.array([10, 30, 40, 50, 70, 90])
arr3 = np.setdiff1d(arr1,arr2)
print(arr3)

[ 0 20 60 80]


In [ ]:
#14 setExclusive-or different elements in sorted order
arr1 = [0,10,20,40,60,80]  
arr2 = [10,30,40,50,70] 
arr3 = np.setdiff1d(arr1,arr2)
arr4 = np.setdiff1d(arr2,arr1)
print(np.sort(np.concatenate([arr3, arr4], axis=0)))

print(np.setxor1d(arr1,arr2))

[ 0 20 30 50 60 70 80]
[ 0 20 30 50 60 70 80]


In [ ]:
#15.a conditions in numpy
a =np.array( [1,2] )
b = np.array([4,5]) 
result = np.where(a > b,True,False)  
print(result)
result2 = np.where(a >= b, True, False)  
print(result2)
result3 = np.where(a < b ,True,False)
print(result3)
result4 = np.where(a<=b,True,False)  
print(result4)

# print(np.logical_and(a > b, a >= b ))
# print(np.logical_and(a < b, a <= b))

[False False]
[False False]
[ True  True]
[ True  True]


In [ ]:
#15.b write an array i to a file 
import csv
arr1 = np.array([ 0, 10 ,20 ,40 ,60 ,80],dtype="int32") 
with open("numpy.csv","w") as f:
    csv.writer(f).writerow(arr1)
    f.write
with open("numpy.csv","r") as f:
    arr2 = csv.reader(f)
    for i in arr2:
        print(np.array(i,dtype="int32"))

np.savetxt("numpy.txt",arr1)
a = np.loadtxt("numpy.txt",delimiter=",")
print(a)


[ 0 10 20 40 60 80]
[]
[ 0. 10. 20. 40. 60. 80.]


In [65]:
#16 convert an arrray into 1d array
arr1 = np.array([[10,20,30],  
[20 ,40 ,50]] ) 
print(arr1.flatten())
print(arr1.ravel())
print(arr1.reshape(1,6))

[10 20 30 20 40 50]
[10 20 30 20 40 50]
[[10 20 30 20 40 50]]


In [ ]:
#17 convert int32 to float64
arr1 = np.array([[2,4,6],
[6,8,10]])
print(f"{arr1}\n Data type of the array arr1 is: {arr1.dtype}")  
arr2 = np.array(arr1,dtype="float64")
print(f"{arr2}\n Data type of the array arr1 is: {arr2.dtype}")  


[[ 2  4  6]
 [ 6  8 10]]
 Data type of the array x is: int64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
 Data type of the array x is: float64


In [ ]:
#18 making daignol elements as 1
arr1 = np.zeros((6,6))
for i in range(len(arr1)):
    arr1[i][i] = 1
print(arr1)

arr2 = np.zeros((6,6))
np.fill_diagonal(arr2,1)
print(arr2)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
#19 given pattern


In [ ]:
#20 concatinate two dimensional array
arr1 = np.array(([[0, 1, 3],
                 [5, 7, 9]] , 
                 [[0, 2, 4], 
                 [6, 8, 10]]))
print(np.array([np.append(arr1[0][0],arr1[1][0]),np.append(arr1[0][1],arr1[1][1])]))
print(np.array([np.concatenate((arr1[0][0],arr1[1][0])),np.concatenate((arr1[0][1],arr1[1][1]))]))

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [ ]:
#21 make an array as immutable
arr1 = np.array([ 5,7,9,6,8,10])
arr1.setflags(write = False)
arr1[0]=6
print(arr1)


AttributeError: 'numpy.ndarray' object has no attribute 'totuple'

In [111]:
#22  multiply every element with 3
def mul(x):
   return x*3

arr1 = np.random.randint(2,9,(3,4))
arr2 = np.ones((3,4))
arr3 =np.vectorize(mul)(arr1)
arr4 = np.vectorize(mul)(arr2)
print(arr1)
print(arr3)
print(arr2)
print(arr4)

[[6 7 3 3]
 [8 5 8 8]
 [4 7 2 5]]
[[18 21  9  9]
 [24 15 24 24]
 [12 21  6 15]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [ ]:
#23 convert array to a list
arr1 = np.array([[0,1],[2,3],[4,5]])
arr2 = arr1.tolist()
print(arr2)

[[0, 1], [2, 3], [4, 5]]


In [129]:
#24 convert array to list 
arr1 = np.array([ 0.26153123, 0.52760141 ,0.5718299 ,0.5927067, 0.7831874 ,0.69746349 ,
0.35399976 ,0.99469633 ,0.0694458 ,0.54711478])
arr2 = np.round(np.array(arr1,dtype="float"),4).tolist()
print(type(arr2))
print(arr2)


<class 'list'>
[0.2615, 0.5276, 0.5718, 0.5927, 0.7832, 0.6975, 0.354, 0.9947, 0.0694, 0.5471]


In [134]:
#25
arr1 = np.array([ 1.60000000e-10 ,1.60000000e+00 ,1.20000000e+03, 2.35000000e-01] ) 
# arr2 = np.round(arr1,3)
np.set_printoptions(precision=3)
print(arr1)

[1.60e-10 1.60e+00 1.20e+03 2.35e-01]


In [144]:
#26 Add Extra Column
arr1 = np.array([[ 10, 20, 30, 100] ,
[ 40 ,50 ,60 ,200]] )
arr2 = np.column_stack((arr1,np.ones((2,1))))
print(arr2)

[[ 10.  20.  30. 100.   1.]
 [ 40.  50.  60. 200.   1.]]
